[build]
command = "npm run prerender"
publish = "dist/chats-micro-services/browser"
functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200

[build.environment]
  NODE_VERSION = "18.18.0"
